<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.apache.pdfbox</groupId>
    <artifactId>pdfbox-parent</artifactId>
    <version>3.0.7</version>
    <relativePath>../parent/pom.xml</relativePath>
  </parent>
  <artifactId>pdfbox-io</artifactId>
  <packaging>bundle</packaging>
  <name>Apache PDFBox io</name>
  <description>The Apache PDFBox library is an open source Java tool for working with PDF documents. 
        This artefact contains IO related classes.</description>
  <inceptionYear>2002</inceptionYear>
  <scm>
    <connection>scm:svn:https://svn.apache.org/repos/asf/pdfbox/tags/3.0.7/io</connection>
    <developerConnection>scm:svn:https://svn.apache.org/repos/asf/pdfbox/tags/3.0.7/io</developerConnection>
    <url>https://svn.apache.org/viewvc/pdfbox/tags/3.0.7/io</url>
  </scm>
  <dependencies>
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>${commons-logging.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Automatic-Module-Name>org.apache.pdfbox.io</Automatic-Module-Name>
          </instructions>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.rat</groupId>
        <artifactId>apache-rat-plugin</artifactId>
        <configuration>
          <inputExcludes>
            <inputExclude>src/test/resources/org/apache/pdfbox/io/*.txt</inputExclude>
          </inputExcludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>iterative-merge</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
              <argLine>-XX:AOTCacheOutput=cache.aot</argLine>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>tree-merge</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
              <argLine>-XX:AOTCacheOutput=cache.aot</argLine>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
